### ISSUE TITLE
Add Parking lot instructions to Home page

### ISSUE THREAD

**Issue by Nightmare1031** [asnow003/haunt-kzo#30]
See mock up:
Graphic header - "Do not drive..."

Text copy:
Your Haunted attraction near me experience begins in the parking lot at the Paw Paw High School (located at 30609 Red Arrow Hwy, Paw Paw MI 49079) where a gang of our crudest has escaped Cypress Hollow to torment the living.  Continuing on the buses you will be met face to face with one of our creatures joining you on the ride to the Attraction.

Please do not attempt to park at Nightmare Realm during show nights, we will redirect you to the Paw Paw High School Parking Lot (located at 30609 Red Arrow Hwy, Paw Paw, Mi 49071).  We understand this may be an inconvenience for some, but we added entertainment through the whole experience to compensate for that.  Thank you!

**Comment by asnow003** [comment]
The parking sections exists on the home page.  Did you need it moved up?

**Comment by Nightmare1031** [comment]
Oh nice I see the changes.  No do not move the parking section up and just move the video and social media section down under parking
